// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace with your actual Firebase configuration from Firebase console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUmWhj71fFxbntWMKrgGhjstOcdnkCHk',
    appId: '1:262840848895:web:df6d5e1db3e00170f997ca',
    messagingSenderId: '262840848895',
    projectId: 'field-project-2624e',
    authDomain: 'field-project-2624e.firebaseapp.com',
    storageBucket: 'field-project-2624e.appspot.com',
    measurementId: 'G-15VVZWBW86',
  );

  // Replace with your actual Firebase configuration from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5xt0t7PQCGRrT_6LwNvY5vNDPPwBRhc',
    appId: '1:262840848895:android:c9054a0675d313baf997ca',
    messagingSenderId: '262840848895',
    projectId: 'field-project-2624e',
    storageBucket: 'field-project-2624e.appspot.com',
  );

  // Replace if you need iOS support
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYS5VrMaMHvC2GI9wFE2AjI2qGN3lGhI',
    appId: '1:262840848895:android:c9054a0675d313baf997ca',
    messagingSenderId: '262840848895',
    projectId: 'field-project-2624e',
    storageBucket: 'field-project-2624e.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.foodDonationApp',
  );
} 